# Generated by Django 3.0.8 on 2020-07-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansewer_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField(max_length=4000)),
                ('id_post_ansewer', models.IntegerField(max_length=500)),
                ('id_dad', models.IntegerField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField(max_length=4000)),
                ('id_dad', models.IntegerField(max_length=500)),
                ('img', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=50)),
                ('ansewer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('personal_description', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
