# Generated by Django 3.0.8 on 2020-07-31 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0003_auto_20200731_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ansewer_post',
            old_name='id_dad',
            new_name='id_create',
        ),
    ]
