# Generated by Django 3.0.8 on 2020-07-31 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0004_auto_20200731_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansewer_post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
