# Generated by Django 3.0.8 on 2020-08-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0008_auto_20200801_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_files'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
