# Generated by Django 3.0.8 on 2020-08-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0010_auto_20200802_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_dad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
