# Generated by Django 3.0.8 on 2020-08-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0011_post_id_dad'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba_imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='prueba_imagen')),
            ],
        ),
        migrations.AddField(
            model_name='ansewer_post',
            name='id_dad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
