# Generated by Django 3.0.8 on 2020-08-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0012_auto_20200803_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba_imagen',
        ),
        migrations.RemoveField(
            model_name='ansewer_post',
            name='id_dad',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_dad',
        ),
    ]
