# Generated by Django 3.0.8 on 2020-08-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0014_auto_20200805_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansewer_post',
            name='title',
        ),
    ]
