# Generated by Django 3.0.8 on 2020-08-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_general', '0015_remove_ansewer_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='image-user.png', upload_to='post_files'),
        ),
    ]
